### ISSUE TITLE
Lack of migrations

### ISSUE THREAD

**Issue by mjaworski** [angvp/django-klingon#15]
After upgrading to Django 1.8 I'm unable to run full migration on my project, with the error occurring when executing following SQL:

`ALTER TABLE "klingon_translation" ADD CONSTRAINT "klin_content_type_id_37544a0e3e8320c7_fk_django_content_type_id" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED`

`django.db.utils.ProgrammingError: relation "django_content_type" does not exist`

After consulting the Django docs:
https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies
it explicitly disallowed for an app with no migrations to depend on the app with migrations (which django.contenttypes is). So for future releases I think migrations should be added declaring the dependency on the contenttypes app.

**Comment by angvp** [comment]
You're completely right, wanna do a pull request? otherwise I'll do it

**Comment by mjaworski** [comment]
Hi,

This is the migration I've added:
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('object_id', models.PositiveIntegerField()),
                ('lang', models.CharField(max_length=5, db_index=True)),
                ('field', models.CharField(max_length=255, db_index=True)),
                ('translation', models.TextField(null=True, blank=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['lang', 'field'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set([('content_type', 'object_id', 'lang', 'field')]),
        ),
    ]
```
as `klingon/migrations/0001_initial.py`, it solved the issue.

**Comment by angvp** [comment]
Nice @mjaworski !, 

I know how to add this, but I'd be better if you fork the repo then add your changes, see https://github.com/angvp/django-klingon/blob/master/CONTRIBUTING.rst#get-started if you don't know/want to do it this way, plus you will have contributions in this project ;), let me know if you want to go with this way, or if you need some help, otherwise I'd do it.

Regards

**Comment by mjaworski** [comment]
Done

**Comment by angvp** [comment]
Awesome, just point the pull request to the branch ``develop`` and we're ready!

**Comment by mjaworski** [comment]
Added new PR to develop branch, might wanna update the contributing doc to mention the branch :)

**Comment by angvp** [comment]
Great!, thanks @mjaworski a new release will come soon
